name: Push-to-EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to EC2 on main branch push
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the files
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install Dependencies
              run: npm install

            - name: Deploy to Server 1
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.HOST_DNS }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  TARGET: ${{ secrets.TARGET_DIR }}

            - name: Configure SSH Key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Restart PM2
              env:
                  REMOTE_HOST: ${{ secrets.HOST_DNS }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  TARGET_DIR: ${{ secrets.TARGET_DIR }}
              run: |
                  ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "$REMOTE_USER@$REMOTE_HOST" << 'EOF'
                  cd $TARGET_DIR
                  if ! pm2 list | grep -q "app1"; then
                      pm2 start
                  else
                      pm2 restart all
                  fi
                  EOF
